### ISSUE TITLE
Authentication based in Passport.js

### ISSUE THREAD

**Issue by WalterLeinert** [Romakita/example-ts-express-decorator#1]
Today I tried to integrale Passport.js but without success.
Can you please give me some hints how to integrate Passport.js correctly (I used strategy local).

Regards,
Walter

**Comment by Romakita** [comment]
Hello WalterLeinert,

I'd just commit an example to use Passport.js with ts-express-decorators [passport-example](https://github.com/Romakita/example-ts-express-decorator/tree/master/example-passport)

I'll find a [`PassportLocalService`](https://github.com/Romakita/example-ts-express-decorator/blob/master/example-passport/services/PassportLocalService.ts) and [`UsersService`](https://github.com/Romakita/example-ts-express-decorator/blob/master/example-passport/services/UsersService.ts) in `services` directory to implement your `LocalStrategy`.

Then in "controllers" directory,  you have the Controller [`PassportCtrl`](https://github.com/Romakita/example-ts-express-decorator/blob/master/example-passport/controllers/passport/PassportCtrl.ts) to mount the `rest/passport/login` route ;)

Finally, in your [ServerLoader](https://github.com/Romakita/example-ts-express-decorator/blob/master/example-passport/Server.ts) you need to add this method:

```typescript
public isAuthenticated(request: Express.Request, response: Express.Response, next: Express.NextFunction): boolean {

        // Just use passport strategy method to know if the user is Authenticated :)
        return request.isAuthenticated();
}
```

To test this example you can use "postman" or other Rest Client, and use this credentials:
```
{
	"email": "claudine.noel@undefined.org",
	"password": "583538e9f26a4de79fee96bd"
}
```
Other credentials are available in [resources/users.json](https://github.com/Romakita/example-ts-express-decorator/blob/master/example-passport/resources/users.json)

See you :)

**Comment by WalterLeinert** [comment]
Hi Romain,

thank you so much! 

Yesterday I experimented and debugged the whole day to get it done, but was'nt successfull.
Today the sun shines again ... (:-) ... it works

Regards,
Walter
