### ISSUE TITLE
Authentication checks do not work as expected

### ISSUE THREAD

**Issue by WalterLeinert** [Romakita/example-ts-express-decorator#3]
After successful integration of the Passport authentication sample in my projekt I tested the REST call authentication:
1) I annotated my controller methods with @Authenticated()
2) I set a breakpoint in my isAuthenticated method

After successful Login and calling a rest method my app stops at the breakpoint, but request.isAuthenticated(); always returns false. The reason is that 'this[property]' in function req.isAuthenticated is always undefined.

Any idea,
regards, Walter

**Comment by Romakita** [comment]
Hello Walter,

I found the problem. In my example I've forgotten to set the session maxAge attribut. So you need fix that like this:

Server.ts:
```typescript
public importMiddlewares(): Server {
        let morgan = require('morgan'),
            cookieParser = require('cookie-parser'),
            bodyParser = require('body-parser'),
            compress = require('compression'),
            methodOverride = require('method-override'),
            session = require('express-session'),
            passport = require('passport');


        this
            .use(morgan('dev'))
            .use(ServerLoader.AcceptMime("application/json"))

            .use(cookieParser())
            .use(compress({}))
            .use(methodOverride())
            .use(bodyParser.json())
            .use(bodyParser.urlencoded({
                extended: true
            }))

            // Configure session used by Passport
            .use(session({
                secret: 'mysecretkey',
                resave: true,
                saveUninitialized: true,
                maxAge: 36000,      /// SET MAXAGE HERE !
                cookie: {
                    path: '/',
                    httpOnly: true,
                    secure: false,
                    maxAge: null
                }
            }))
            // Configure passport JS
            .use(passport.initialize())
            .use(passport.session());

        return this;
    }
```
After, you need to fix a problem binding in PassportLocalService constructor.
```typescript
@Service()
export default class PassportLocalService {

    constructor(private usersService: UsersService){

        // used to serialize the user for the session
        Passport.serializeUser(PassportLocalService.serialize);

        // used to deserialize the user
        Passport.deserializeUser(this.deserialize.bind(this)); /// ADD bind(this)
    }

     /// and change method declaration of deserialize. previously, I used arrow function.
     public deserialize(id, done) {
         done(null, this.usersService.find(id));
     };
```
I don't understand why the context is lost but with `.bind(this)` the code work fine :/

Sorry for this errors,
Regards, Romain

**Comment by WalterLeinert** [comment]
Hi Romain,

Thank you for your immediate response.
Because I started developing with node and angular2 recently after developing Systems in c#/.net and Java for years, I have some starter issues.
One question is how to create a deployment Package which contains only the required libraries/node_modules for Production deployment?

Regards,
Walter

**Comment by Romakita** [comment]
No problem walter ;) 

To filter some files when you publish your node module you can use a `.npmignore` file. It does work as same as a `.gitignore` file.

You can find as example, my .npmignore on ts-express-decorators in the 1.2.0 branch :)

**Comment by Romakita** [comment]
Sorry i'd just understand your question.

For a production deployement you must add your node modules in depedencies attribut in your package.json. 

All node module not needed for prod must be placed in devDepedencies attribut. 

When you start your deployement on your prod server you must add a environment variable:

```
NODE_ENV=production
```
 And when you install package you can use:

```
npm install --production
```

This flag install only depedencies without devDepedencies module.

Note : this command can be used in your local environment to test that.
